### ISSUE TITLE
when have multiple job,only run  last one

### ISSUE THREAD

**Issue by ynat** [Wkalmar/QuartzDI.Demo#1]
when have multiple job,only run  last one,the scheduler.JobFactory will be reset

**Comment by ynat** [comment]
private static async Task ScheduleJob(IServiceProvider serviceProvider)
        {
            var props = new NameValueCollection
            {
                { "quartz.serializer.type", "binary" }
            };
            var factory = new StdSchedulerFactory(props);
            var sched = await factory.GetScheduler();

            await sched.Start();
            sched.JobFactory = new DemoJobFactory(serviceProvider);
            var job = JobBuilder.Create<DemoJob>()
                .WithIdentity("myJob", "group1")
                .Build();
            var trigger = TriggerBuilder.Create()
                .WithIdentity("myTrigger", "group1")
                .StartNow()
                .WithSimpleSchedule(x => x
                    .WithIntervalInSeconds(5)
                    .RepeatForever())
            .Build();
            await sched.ScheduleJob(job, trigger);


            sched.JobFactory = new DemoJob2Factory(serviceProvider);
            var job2 = JobBuilder.Create<DemoJob2>()
                .WithIdentity("myJob2", "group2")
                .Build();
            var trigger2 = TriggerBuilder.Create()
                .WithIdentity("myTrigger2", "group2")
                .StartNow()
                .WithSimpleSchedule(x => x
                    .WithIntervalInSeconds(5)
                    .RepeatForever())
            .Build();
            await sched.ScheduleJob(job2, trigger2);
        }

it's run  DemoJob2  two, DemoJob is not work

**Comment by icmr** [comment]
ye, I have the same issue. It can only create the last job and run it.

How can I fixt it?

**Comment by Wkalmar** [comment]
I think it's because you overwrite
```
sched.JobFactory = new DemoJobFactory(serviceProvider);
```
with
```
sched.JobFactory = new DemoJob2Factory(serviceProvider);
```
I really doubt you could have both factories work at the same time this way.
